/*
  One object per certificate. The file path must match the PDF exactly.
  rollNo, fatherName, searchNames, and recordLabel are optional.
  Search can use rollNo or searchNames without showing them on the result card.
*/
const certificates = [

  // Little Geniuses
  {
    name: "Abdul Hadi Ahmed Qureshi",
    rollNo: "870790",
    course: "Little Geniuses",
    batch: "1",
    file: "certificates/little-geniuses/Abdul Hadi Ahmed Qureshi-SMIT-2026-LG-B1-221.pdf",
  },
  {
    name: "Muhammad Hassaan Elahi",
    rollNo: "870753",
    course: "Little Geniuses",
    batch: "1",
    file: "certificates/little-geniuses/Muhammad Hassaan Elahi-SMIT-2026-LG-B1-222.pdf",
  },
  {
    name: "Muhammad Affan Hussain",
    rollNo: "874529",
    course: "Little Geniuses",
    batch: "1",
    file: "certificates/little-geniuses/Muhammad Affan Hussain-SMIT-2026-LG-B1-223.pdf",
  },
  {
    name: "Ali Hussain",
    rollNo: "857401",
    course: "Little Geniuses",
    batch: "1",
    file: "certificates/little-geniuses/Ali Hussain-SMIT-2026-LG-B1-224.pdf",
  },
  {
    name: "Abeer Ali",
    rollNo: "858003",
    course: "Little Geniuses",
    batch: "1",
    file: "certificates/little-geniuses/Abeer Ali-SMIT-2026-LG-B1-225.pdf",
  },
  {
    name: "Ahyan Naveed",
    rollNo: "871073",
    course: "Little Geniuses",
    batch: "1",
    file: "certificates/little-geniuses/Ahyan Naveed-SMIT-2026-LG-B1-226.pdf",
  },
  {
    name: "Muhammad Moiz Khan",
    rollNo: "871539",
    course: "Little Geniuses",
    batch: "1",
    file: "certificates/little-geniuses/Muhammad Moiz Khan-SMIT-2026-LG-B1-227.pdf",
  },
  {
    name: "Shaheer Rao",
    rollNo: "867048",
    course: "Little Geniuses",
    batch: "1",
    file: "certificates/little-geniuses/Shaheer Rao-SMIT-2026-LG-B1-228.pdf",
  },
  {
    name: "Maaz Khan",
    rollNo: "871527",
    course: "Little Geniuses",
    batch: "1",
    file: "certificates/little-geniuses/Maaz Khan-SMIT-2026-LG-B1-229.pdf",
  },
  {
    name: "Muhammad Burhan Azeem",
    rollNo: "871978",
    course: "Little Geniuses",
    batch: "1",
    file: "certificates/little-geniuses/Muhammad Burhan Azeem-SMIT-2026-LG-B1-230.pdf",
  },
  {
    name: "M Najaf Ameer Sahu",
    rollNo: "867092",
    course: "Little Geniuses",
    batch: "1",
    file: "certificates/little-geniuses/M Najaf Ameer Sahu-SMIT-2026-LG-B1-231.pdf",
  },
  {
    name: "Abdul Hannan",
    rollNo: "871660",
    course: "Little Geniuses",
    batch: "1",
    file: "certificates/little-geniuses/Abdul Hannan-SMIT-2026-LG-B1-232.pdf",
  },
  {
    name: "Muhammad Ahmed",
    rollNo: "872011",
    course: "Little Geniuses",
    batch: "1",
    file: "certificates/little-geniuses/Muhammad Ahmed-SMIT-2026-LG-B1-233.pdf",
  },
  {
    name: "Umar Hameed",
    rollNo: "861649",
    course: "Little Geniuses",
    batch: "1",
    file: "certificates/little-geniuses/Umar Hameed-SMIT-2026-LG-B1-234.pdf",
  },
  {
    name: "Abdul Moeed",
    rollNo: "871374",
    course: "Little Geniuses",
    batch: "1",
    file: "certificates/little-geniuses/Abdul Moeed-SMIT-2026-LG-B1-235.pdf",
  },
  {
    name: "Ahmed Nadeem",
    rollNo: "866801",
    course: "Little Geniuses",
    batch: "1",
    file: "certificates/little-geniuses/Ahmed Nadeem-SMIT-2026-LG-B1-236.pdf",
  },
  {
    name: "Muhammad Faiq Behzad",
    rollNo: "871201",
    course: "Little Geniuses",
    batch: "1",
    file: "certificates/little-geniuses/Muhammad Faiq Behzad-SMIT-2026-LG-B1-237.pdf",
  },

  // AI & Game Creators
  {
    name: "Muhammad Hassan Tariq",
    rollNo: "871880",
    course: "AI & Game Creators",
    batch: "1",
    file: "certificates/ai-game-creators/Muhammad Hassan Tariq-SMIT-2026-AIG-B1-246.pdf",
  },
  {
    name: "Muhammad Anas Ghuman",
    rollNo: "871781",
    course: "AI & Game Creators",
    batch: "1",
    file: "certificates/ai-game-creators/Muhammad Anas Ghuman-SMIT-2026-AIG-B1-247.pdf",
  },
  {
    name: "Abdul Haseeb Khan",
    rollNo: "876928",
    course: "AI & Game Creators",
    batch: "1",
    file: "certificates/ai-game-creators/Abdul Haseeb Khan-SMIT-2026-AIG-B1-248.pdf",
  },
  {
    name: "Muhammad Taimur Asad",
    rollNo: "872866",
    course: "AI & Game Creators",
    batch: "1",
    file: "certificates/ai-game-creators/Muhammad Taimur Asad-SMIT-2026-AIG-B1-249.pdf",
  },
  {
    name: "Hassan Raza",
    rollNo: "873383",
    course: "AI & Game Creators",
    batch: "1",
    file: "certificates/ai-game-creators/Hassan Raza-SMIT-2026-AIG-B1-250.pdf",
  },
  {
    name: "M Hassan",
    rollNo: "872450",
    course: "AI & Game Creators",
    batch: "1",
    file: "certificates/ai-game-creators/M Hassan-SMIT-2026-AIG-B1-251.pdf",
  },
  // Certificate 252 for Muhammad Hassan Tariq is omitted until its PDF exists.
  {
    name: "Mohammad Wasay Ullah",
    rollNo: "872196",
    course: "AI & Game Creators",
    batch: "1",
    file: "certificates/ai-game-creators/Mohammad Wasay Ullah-SMIT-2026-AIG-B1-253.pdf",
  },
  {
    name: "Muhammad Wasif Hameed",
    rollNo: "871391",
    course: "AI & Game Creators",
    batch: "1",
    file: "certificates/ai-game-creators/Muhammad Wasif Hameed-SMIT-2026-AIG-B1-254.pdf",
  },
  {
    name: "Mohammad Hashir",
    rollNo: "872185",
    course: "AI & Game Creators",
    batch: "1",
    file: "certificates/ai-game-creators/Mohammad Hashir-SMIT-2026-AIG-B1-255.pdf",
  },
  {
    name: "Syed Muneeb Ali",
    rollNo: "872761",
    course: "AI & Game Creators",
    batch: "1",
    file: "certificates/ai-game-creators/Syed Muneeb Ali-SMIT-2026-AIG-B1-256.pdf",
  },
  {
    name: "Ubaid Waseem Lodhi",
    rollNo: "872563",
    course: "AI & Game Creators",
    batch: "1",
    file: "certificates/ai-game-creators/Ubaid Waseem Lodhi-SMIT-2026-AIG-B1-257.pdf",
  },
  {
    name: "M Ahmed Raza Nasir",
    rollNo: "858319",
    course: "AI & Game Creators",
    batch: "1",
    file: "certificates/ai-game-creators/M Ahmed Raza Nasir-SMIT-2026-AIG-B1-258.pdf",
  },
  {
    name: "Muhammad Anas Ghuman",
    rollNo: "871781",
    course: "AI & Game Creators",
    batch: "1",
    file: "certificates/ai-game-creators/Muhammad Anas Ghuman-SMIT-2026-AIG-B1-259.pdf",
  },
  {
    name: "Abdul Hannan",
    rollNo: "871671",
    course: "AI & Game Creators",
    batch: "1",
    file: "certificates/ai-game-creators/Abdul Hannan-SMIT-2026-AIG-B1-260.pdf",
  },
  {
    name: "Muhammad Qasim Azeem",
    rollNo: "866990",
    course: "AI & Game Creators",
    batch: "1",
    file: "certificates/ai-game-creators/Muhammad Qasim Azeem-SMIT-2026-AIG-B1-261.pdf",
  },
  {
    name: "Muhammad Shehryar",
    rollNo: "872154",
    course: "AI & Game Creators",
    batch: "1",
    file: "certificates/ai-game-creators/Muhammad Shehryar-SMIT-2026-AIG-B1-262.pdf",
  },
  {
    name: "Muhammd Sarmad Waqas Rao",
    rollNo: "871610",
    course: "AI & Game Creators",
    batch: "1",
    file: "certificates/ai-game-creators/Muhammd Sarmad Waqas Rao-SMIT-2026-AIG-B1-263.pdf",
  },
  {
    name: "Mohammad Hashir",
    rollNo: "872185",
    course: "AI & Game Creators",
    batch: "1",
    file: "certificates/ai-game-creators/Mohammad Hashir-SMIT-2026-AIG-B1-264.pdf",
  },
  {
    name: "Muhammad Saad Ibne Waqas",
    rollNo: "871619",
    course: "AI & Game Creators",
    batch: "1",
    file: "certificates/ai-game-creators/Muhammad Saad Ibne Waqas-SMIT-2026-AIG-B1-265.pdf",
  },
  {
    name: "Muhammad Abdullah Sufyan",
    rollNo: "872500",
    course: "AI & Game Creators",
    batch: "1",
    file: "certificates/ai-game-creators/Muhammad Abdullah Sufyan-SMIT-2026-AIG-B1-266.pdf",
  },
  {
    name: "M Saqib Ameer Sahu",
    rollNo: "867087",
    course: "AI & Game Creators",
    batch: "1",
    file: "certificates/ai-game-creators/M Saqib Ameer Sahu-SMIT-2026-AIG-B1-267.pdf",
  },
  {
    name: "Umar Hameed",
    rollNo: "861649",
    course: "AI & Game Creators",
    batch: "1",
    file: "certificates/ai-game-creators/Umar Hameed-SMIT-2026-AIG-B1-268.pdf",
  },

  // Little Geniuses — additional certificates
  {
    name: "Dawood Ahmed Gul",
    course: "Little Geniuses",
    batch: "1",
    file: "certificates/lg-new2/03-1.pdf",
  },
  {
    name: "Muhammad Sohaib Qamar",
    course: "Little Geniuses",
    batch: "1",
    file: "certificates/lg-new2/03-2.pdf",
  },
  {
    name: "Muhammad Ammar",
    course: "Little Geniuses",
    batch: "1",
    file: "certificates/lg-new2/03-3.pdf",
  },
  {
    name: "Mahammad Aakif Hameed",
    course: "Little Geniuses",
    batch: "1",
    file: "certificates/lg-new2/03-4.pdf",
  },
  {
    name: "Muhammad Saqlain Raza",
    course: "Little Geniuses",
    batch: "1",
    file: "certificates/lg-new2/03-5.pdf",
  },
  {
    name: "Muhammad Zulqarnain Raza",
    course: "Little Geniuses",
    batch: "1",
    file: "certificates/lg-new2/03-6.pdf",
  },
  {
    name: "Mohammad Rehan Khan",
    course: "Little Geniuses",
    batch: "1",
    file: "certificates/lg-new2/03-7.pdf",
  },

  // Bahria Web B1 — boys
  {
    name: "Abdullah Arshad",
    course: "Web App Development",
    batch: "1",
    file: "certificates/bahria-web-b1-eab1/boys/01.Abdullah Arshad.pdf",
  },
  {
    name: "Abdul Moeed",
    course: "Web App Development",
    batch: "1",
    file: "certificates/bahria-web-b1-eab1/boys/02.Abdul Moeed.pdf",
  },
  {
    name: "Ammar Ahmed",
    course: "Web App Development",
    batch: "1",
    file: "certificates/bahria-web-b1-eab1/boys/03.Ammar Ahmed.pdf",
  },
  {
    name: "Awais Tahir",
    course: "Web App Development",
    batch: "1",
    file: "certificates/bahria-web-b1-eab1/boys/04.Awais Tahir.pdf",
  },
  {
    name: "Azan Ali",
    course: "Web App Development",
    batch: "1",
    file: "certificates/bahria-web-b1-eab1/boys/05.Azan Ali.pdf",
  },
  {
    name: "Hafiz Muhammad Usman Khaliq",
    course: "Web App Development",
    batch: "1",
    searchNames: ["Hafiz Muhammad Usman Khan"],
    file: "certificates/bahria-web-b1-eab1/boys/06.Hafiz Muhammad Usman Khan.pdf",
  },
  {
    name: "Hasnain Yasir",
    course: "Web App Development",
    batch: "1",
    file: "certificates/bahria-web-b1-eab1/boys/07.Hasnain Yasir.pdf",
  },
  {
    name: "Huzaifa Ahmed",
    course: "Web App Development",
    batch: "1",
    file: "certificates/bahria-web-b1-eab1/boys/08.Huzaifa Ahmed.pdf",
  },
  {
    name: "Muhammad Absar Imran",
    course: "Web App Development",
    batch: "1",
    file: "certificates/bahria-web-b1-eab1/boys/09.Muhammad Absar Imran.pdf",
  },
  {
    name: "Muhammad Ali",
    course: "Web App Development",
    batch: "1",
    file: "certificates/bahria-web-b1-eab1/boys/10.Muhammad Ali.pdf",
  },
  {
    name: "Muhammad Ayyan",
    course: "Web App Development",
    batch: "1",
    file: "certificates/bahria-web-b1-eab1/boys/11.Muhammad Ayyan.pdf",
  },
  {
    name: "Muhammad Faizan",
    course: "Web App Development",
    batch: "1",
    searchNames: ["Faizan Abrar"],
    recordLabel: "Faizan Abrar",
    file: "certificates/bahria-web-b1-eab1/boys/12.Faizan Abrar.pdf",
  },
  {
    name: "Muhammad Faizan",
    course: "Web App Development",
    batch: "1",
    searchNames: ["Faizan Ishtiaq"],
    recordLabel: "Faizan Ishtiaq",
    file: "certificates/bahria-web-b1-eab1/boys/13.Faizan Ishtiaq.pdf",
  },
  {
    name: "Muhammad Hassan",
    course: "Web App Development",
    batch: "1",
    file: "certificates/bahria-web-b1-eab1/boys/14.Muhammad Hassan.pdf",
  },
  {
    name: "Muhammad Jawad",
    course: "Web App Development",
    batch: "1",
    file: "certificates/bahria-web-b1-eab1/boys/15.Muhammad Jawad.pdf",
  },
  {
    name: "Muhammad Talha",
    course: "Web App Development",
    batch: "1",
    file: "certificates/bahria-web-b1-eab1/boys/16.Muhammad Talha.pdf",
  },
  {
    name: "Muhammad Talha Shafqat Baig",
    course: "Web App Development",
    batch: "1",
    file: "certificates/bahria-web-b1-eab1/boys/17.Muhammad Talha Shafqat Baig.pdf",
  },
  {
    name: "Rao Muhammad Ibrahim",
    course: "Web App Development",
    batch: "1",
    file: "certificates/bahria-web-b1-eab1/boys/18.Rao Muhammad Ibrahim.pdf",
  },
  {
    name: "Saim Mujahid",
    course: "Web App Development",
    batch: "1",
    file: "certificates/bahria-web-b1-eab1/boys/19.Saim Mujahid.pdf",
  },
  {
    name: "Saqlain Ur Razzaq",
    course: "Web App Development",
    batch: "1",
    file: "certificates/bahria-web-b1-eab1/boys/20.Saqlain Ur Razzaq.pdf",
  },
  {
    name: "Sarmad Tabassum",
    course: "Web App Development",
    batch: "1",
    file: "certificates/bahria-web-b1-eab1/boys/21.Sarmad Tabassum.pdf",
  },
  {
    name: "Syed Hashir Imran Ali",
    course: "Web App Development",
    batch: "1",
    file: "certificates/bahria-web-b1-eab1/boys/22.Syed Hashir Imran Ali.pdf",
  },
  {
    name: "Talha Khan",
    course: "Web App Development",
    batch: "1",
    file: "certificates/bahria-web-b1-eab1/boys/23.Talha Khan.pdf",
  },
  {
    name: "Umar Abbas",
    course: "Web App Development",
    batch: "1",
    file: "certificates/bahria-web-b1-eab1/boys/24.Umar Abbas.pdf",
  },
  {
    name: "Zarar Ahmed",
    course: "Web App Development",
    batch: "1",
    file: "certificates/bahria-web-b1-eab1/boys/25.Zarar Ahmed.pdf",
  },

  // Bahria Web B1 — girls
  {
    name: "Aiman Fatima",
    course: "Web App Development",
    batch: "1",
    file: "certificates/bahria-web-b1-eab1/girls/01.pdf",
  },
  {
    name: "Amber Zahra",
    course: "Web App Development",
    batch: "1",
    file: "certificates/bahria-web-b1-eab1/girls/02.pdf",
  },
  {
    name: "Anabia Rao",
    course: "Web App Development",
    batch: "1",
    file: "certificates/bahria-web-b1-eab1/girls/03.pdf",
  },
  {
    name: "Ansa Rasheed",
    course: "Web App Development",
    batch: "1",
    file: "certificates/bahria-web-b1-eab1/girls/04.pdf",
  },
  {
    name: "Aqsa Majid",
    course: "Web App Development",
    batch: "1",
    file: "certificates/bahria-web-b1-eab1/girls/05.pdf",
  },
  {
    name: "Areeba Iftikhar Kayani",
    course: "Web App Development",
    batch: "1",
    file: "certificates/bahria-web-b1-eab1/girls/06.pdf",
  },
  {
    name: "Attia Idrees",
    course: "Web App Development",
    batch: "1",
    file: "certificates/bahria-web-b1-eab1/girls/07.pdf",
  },
  {
    name: "Ayesha Azhar",
    course: "Web App Development",
    batch: "1",
    file: "certificates/bahria-web-b1-eab1/girls/08.pdf",
  },
  {
    name: "Ayesha Imran",
    course: "Web App Development",
    batch: "1",
    file: "certificates/bahria-web-b1-eab1/girls/09.pdf",
  },
  {
    name: "Dua Shafiq",
    course: "Web App Development",
    batch: "1",
    file: "certificates/bahria-web-b1-eab1/girls/10.pdf",
  },
  {
    name: "Iqra Noor",
    course: "Web App Development",
    batch: "1",
    file: "certificates/bahria-web-b1-eab1/girls/11.pdf",
  },
  {
    name: "Khansa Mansoor",
    course: "Web App Development",
    batch: "1",
    file: "certificates/bahria-web-b1-eab1/girls/12.pdf",
  },
  {
    name: "Laiba Bibi",
    course: "Web App Development",
    batch: "1",
    file: "certificates/bahria-web-b1-eab1/girls/13.pdf",
  },
  {
    name: "Laiba Ishtiaq",
    course: "Web App Development",
    batch: "1",
    file: "certificates/bahria-web-b1-eab1/girls/14.pdf",
  },
  {
    name: "Laiba Sattar",
    course: "Web App Development",
    batch: "1",
    file: "certificates/bahria-web-b1-eab1/girls/15.pdf",
  },
  {
    name: "Laiba Shabbir",
    course: "Web App Development",
    batch: "1",
    file: "certificates/bahria-web-b1-eab1/girls/16.pdf",
  },
  {
    name: "Lubna Liaqat",
    course: "Web App Development",
    batch: "1",
    file: "certificates/bahria-web-b1-eab1/girls/17.pdf",
  },
  {
    name: "Maira Manzoor",
    course: "Web App Development",
    batch: "1",
    file: "certificates/bahria-web-b1-eab1/girls/18.pdf",
  },
  {
    name: "Maryam Khalid",
    course: "Web App Development",
    batch: "1",
    file: "certificates/bahria-web-b1-eab1/girls/19.pdf",
  },
  {
    name: "Masooma Zahra",
    course: "Web App Development",
    batch: "1",
    file: "certificates/bahria-web-b1-eab1/girls/20.pdf",
  },
  {
    name: "Muqadas Fatima",
    course: "Web App Development",
    batch: "1",
    file: "certificates/bahria-web-b1-eab1/girls/21.pdf",
  },
  {
    name: "Nabeeha Asif",
    course: "Web App Development",
    batch: "1",
    file: "certificates/bahria-web-b1-eab1/girls/22.pdf",
  },
  {
    name: "Nadia Mosaddiq",
    course: "Web App Development",
    batch: "1",
    file: "certificates/bahria-web-b1-eab1/girls/23.pdf",
  },
  {
    name: "Nimra Irshad",
    course: "Web App Development",
    batch: "1",
    file: "certificates/bahria-web-b1-eab1/girls/24.pdf",
  },
  {
    name: "Nimra Naseer",
    course: "Web App Development",
    batch: "1",
    file: "certificates/bahria-web-b1-eab1/girls/25.pdf",
  },
  {
    name: "Noorulain",
    course: "Web App Development",
    batch: "1",
    file: "certificates/bahria-web-b1-eab1/girls/26.pdf",
  },
  {
    name: "Rabia Imran",
    course: "Web App Development",
    batch: "1",
    file: "certificates/bahria-web-b1-eab1/girls/27.pdf",
  },
  {
    name: "Rahat Sarwar",
    course: "Web App Development",
    batch: "1",
    file: "certificates/bahria-web-b1-eab1/girls/28.pdf",
  },
  {
    name: "Saba Kainat",
    course: "Web App Development",
    batch: "1",
    file: "certificates/bahria-web-b1-eab1/girls/29.pdf",
  },
  {
    name: "Saba Muntaha",
    course: "Web App Development",
    batch: "1",
    file: "certificates/bahria-web-b1-eab1/girls/30.pdf",
  },
  {
    name: "Saba Zubair",
    course: "Web App Development",
    batch: "1",
    file: "certificates/bahria-web-b1-eab1/girls/31.pdf",
  },
  {
    name: "Sahrish Fatima",
    course: "Web App Development",
    batch: "1",
    file: "certificates/bahria-web-b1-eab1/girls/32.pdf",
  },
  {
    name: "Saniyah Khan",
    course: "Web App Development",
    batch: "1",
    file: "certificates/bahria-web-b1-eab1/girls/33.pdf",
  },
  {
    name: "Shagufta Liaqat",
    course: "Web App Development",
    batch: "1",
    file: "certificates/bahria-web-b1-eab1/girls/34.pdf",
  },
  {
    name: "Shumaila Abbas",
    course: "Web App Development",
    batch: "1",
    file: "certificates/bahria-web-b1-eab1/girls/35.pdf",
  },
  {
    name: "Sidra Tul Muntaha",
    course: "Web App Development",
    batch: "1",
    file: "certificates/bahria-web-b1-eab1/girls/36.pdf",
  },
  {
    name: "Tabeena Misal",
    course: "Web App Development",
    batch: "1",
    file: "certificates/bahria-web-b1-eab1/girls/37.pdf",
  },
  {
    name: "Tahira Atiq",
    course: "Web App Development",
    batch: "1",
    file: "certificates/bahria-web-b1-eab1/girls/38.pdf",
  },
  {
    name: "Tahreem Zahra",
    course: "Web App Development",
    batch: "1",
    file: "certificates/bahria-web-b1-eab1/girls/39.pdf",
  },
  {
    name: "Urooj Fatima",
    course: "Web App Development",
    batch: "1",
    file: "certificates/bahria-web-b1-eab1/girls/40.pdf",
  },
  {
    name: "Yumama Waseem",
    course: "Web App Development",
    batch: "1",
    file: "certificates/bahria-web-b1-eab1/girls/41.pdf",
  },
  {
    name: "Yumna Waseem",
    course: "Web App Development",
    batch: "1",
    file: "certificates/bahria-web-b1-eab1/girls/42.pdf",
  },
  {
    name: "Zaynah Khan",
    course: "Web App Development",
    batch: "1",
    file: "certificates/bahria-web-b1-eab1/girls/43.pdf",
  },
];
