/*
  The certificate portal uses this list as its source of truth.
  Add one object per certificate. The PDF filename can be anything; simply put
  its exact path in `file`. Do not add phone numbers or email addresses here.
*/
const certificates = [
  [
    "Abdul Hadi Ahmed Qureshi",
    "870790",
    "Little Geniuses",
    "little-geniuses/Abdul Hadi Ahmed Qureshi-SMIT-2026-LG-B1-221.pdf",
  ],
  [
    "Muhammad Hassaan Elahi",
    "870753",
    "Little Geniuses",
    "little-geniuses/Muhammad Hassaan Elahi-SMIT-2026-LG-B1-222.pdf",
  ],
  [
    "Muhammad Affan Hussain",
    "874529",
    "Little Geniuses",
    "little-geniuses/Muhammad Affan Hussain-SMIT-2026-LG-B1-223.pdf",
  ],
  [
    "Ali Hussain",
    "857401",
    "Little Geniuses",
    "little-geniuses/Ali Hussain-SMIT-2026-LG-B1-224.pdf",
  ],
  [
    "Abeer Ali",
    "858003",
    "Little Geniuses",
    "little-geniuses/Abeer Ali-SMIT-2026-LG-B1-225.pdf",
  ],
  [
    "Ahyan Naveed",
    "871073",
    "Little Geniuses",
    "little-geniuses/Ahyan Naveed-SMIT-2026-LG-B1-226.pdf",
  ],
  [
    "Muhammad Moiz Khan",
    "871539",
    "Little Geniuses",
    "little-geniuses/Muhammad Moiz Khan-SMIT-2026-LG-B1-227.pdf",
  ],
  [
    "Shaheer Rao",
    "867048",
    "Little Geniuses",
    "little-geniuses/Shaheer Rao-SMIT-2026-LG-B1-228.pdf",
  ],
  [
    "Maaz Khan",
    "871527",
    "Little Geniuses",
    "little-geniuses/Maaz Khan-SMIT-2026-LG-B1-229.pdf",
  ],
  [
    "Muhammad Burhan Azeem",
    "871978",
    "Little Geniuses",
    "little-geniuses/Muhammad Burhan Azeem-SMIT-2026-LG-B1-230.pdf",
  ],
  [
    "M Najaf Ameer Sahu",
    "867092",
    "Little Geniuses",
    "little-geniuses/M Najaf Ameer Sahu-SMIT-2026-LG-B1-231.pdf",
  ],
  [
    "Abdul Hannan",
    "871660",
    "Little Geniuses",
    "little-geniuses/Abdul Hannan-SMIT-2026-LG-B1-232.pdf",
  ],
  [
    "Muhammad Ahmed",
    "872011",
    "Little Geniuses",
    "little-geniuses/Muhammad Ahmed-SMIT-2026-LG-B1-233.pdf",
  ],
  [
    "Umar Hameed",
    "861649",
    "Little Geniuses",
    "little-geniuses/Umar Hameed-SMIT-2026-LG-B1-234.pdf",
  ],
  [
    "Abdul Moeed",
    "871374",
    "Little Geniuses",
    "little-geniuses/Abdul Moeed-SMIT-2026-LG-B1-235.pdf",
  ],
  [
    "Ahmed Nadeem",
    "866801",
    "Little Geniuses",
    "little-geniuses/Ahmed Nadeem-SMIT-2026-LG-B1-236.pdf",
  ],
  [
    "Muhammad Faiq Behzad",
    "871201",
    "Little Geniuses",
    "little-geniuses/Muhammad Faiq Behzad-SMIT-2026-LG-B1-237.pdf",
  ],
  [
    "Muhammad Hassan Tariq",
    "871880",
    "AI & Game Creators",
    "ai-game-creators/Muhammad Hassan Tariq-SMIT-2026-AIG-B1-246.pdf",
  ],
  [
    "Muhammad Anas Ghuman",
    "871781",
    "AI & Game Creators",
    "ai-game-creators/Muhammad Anas Ghuman-SMIT-2026-AIG-B1-247.pdf",
  ],
  [
    "Abdul Haseeb Khan",
    "876928",
    "AI & Game Creators",
    "ai-game-creators/Abdul Haseeb Khan-SMIT-2026-AIG-B1-248.pdf",
  ],
  [
    "Muhammad Taimur Asad",
    "872866",
    "AI & Game Creators",
    "ai-game-creators/Muhammad Taimur Asad-SMIT-2026-AIG-B1-249.pdf",
  ],
  [
    "Hassan Raza",
    "873383",
    "AI & Game Creators",
    "ai-game-creators/Hassan Raza-SMIT-2026-AIG-B1-250.pdf",
  ],
  [
    "M Hassan",
    "872450",
    "AI & Game Creators",
    "ai-game-creators/M Hassan-SMIT-2026-AIG-B1-251.pdf",
  ],
  [
    "Muhammad Hassan Tariq",
    "871880",
    "AI & Game Creators",
    "ai-game-creators/Muhammad Hassan Tariq-SMIT-2026-AIG-B1-252.pdf",
  ],
  [
    "Mohammad Wasay Ullah",
    "872196",
    "AI & Game Creators",
    "ai-game-creators/Mohammad Wasay Ullah-SMIT-2026-AIG-B1-253.pdf",
  ],
  [
    "Muhammad Wasif Hameed",
    "871391",
    "AI & Game Creators",
    "ai-game-creators/Muhammad Wasif Hameed-SMIT-2026-AIG-B1-254.pdf",
  ],
  [
    "Mohammad Hashir",
    "872185",
    "AI & Game Creators",
    "ai-game-creators/Mohammad Hashir-SMIT-2026-AIG-B1-255.pdf",
  ],
  [
    "Syed Muneeb Ali",
    "872761",
    "AI & Game Creators",
    "ai-game-creators/Syed Muneeb Ali-SMIT-2026-AIG-B1-256.pdf",
  ],
  [
    "Ubaid Waseem Lodhi",
    "872563",
    "AI & Game Creators",
    "ai-game-creators/Ubaid Waseem Lodhi-SMIT-2026-AIG-B1-257.pdf",
  ],
  [
    "M Ahmed Raza Nasir",
    "858319",
    "AI & Game Creators",
    "ai-game-creators/M Ahmed Raza Nasir-SMIT-2026-AIG-B1-258.pdf",
  ],
  [
    "Muhammad Anas Ghuman",
    "871781",
    "AI & Game Creators",
    "ai-game-creators/Muhammad Anas Ghuman-SMIT-2026-AIG-B1-259.pdf",
  ],
  [
    "Abdul Hannan",
    "871671",
    "AI & Game Creators",
    "ai-game-creators/Abdul Hannan-SMIT-2026-AIG-B1-260.pdf",
  ],
  [
    "Muhammad Qasim Azeem",
    "866990",
    "AI & Game Creators",
    "ai-game-creators/Muhammad Qasim Azeem-SMIT-2026-AIG-B1-261.pdf",
  ],
  [
    "Muhammad Shehryar",
    "872154",
    "AI & Game Creators",
    "ai-game-creators/Muhammad Shehryar-SMIT-2026-AIG-B1-262.pdf",
  ],
  [
    "Muhammd Sarmad Waqas Rao",
    "871610",
    "AI & Game Creators",
    "ai-game-creators/Muhammd Sarmad Waqas Rao-SMIT-2026-AIG-B1-263.pdf",
  ],
  [
    "Mohammad Hashir",
    "872185",
    "AI & Game Creators",
    "ai-game-creators/Mohammad Hashir-SMIT-2026-AIG-B1-264.pdf",
  ],
  [
    "Muhammad Saad Ibne Waqas",
    "871619",
    "AI & Game Creators",
    "ai-game-creators/Muhammad Saad Ibne Waqas-SMIT-2026-AIG-B1-265.pdf",
  ],
  [
    "Muhammad Abdullah Sufyan",
    "872500",
    "AI & Game Creators",
    "ai-game-creators/Muhammad Abdullah Sufyan-SMIT-2026-AIG-B1-266.pdf",
  ],
  [
    "M Saqib Ameer Sahu",
    "867087",
    "AI & Game Creators",
    "ai-game-creators/M Saqib Ameer Sahu-SMIT-2026-AIG-B1-267.pdf",
  ],
  [
    "Umar Hameed",
    "861649",
    "AI & Game Creators",
    "ai-game-creators/Umar Hameed-SMIT-2026-AIG-B1-268.pdf",
  ],
].map(([name, rollNo, course, file]) => ({
  name,
  rollNo,
  course,
  batch: "B1",
  fatherName: "",
  file: `certificates/${file}`,
}));
